### ISSUE TITLE
Phonegap Build 3.0.0 does not copy all config.xml paramaters

### ISSUE THREAD

**Issue by dordal** [phonegap/phonegap-cli#167] opened 2013-09-15 05:37 UTC
The build command in phonegap 3.0.0 does not copy all the `config.xml` parameters to the build environments. 

First, the version:

```
David-Ordals-MacBook-Pro:Development dordal$ phonegap -v
3.0.0-0.14.3
```

Now, the example:

```
David-Ordals-MacBook-Pro:Development dordal$ phonegap create test123 com.test.test123 Test123
[phonegap] created project at /Users/dordal/Documents/Development/test123
David-Ordals-MacBook-Pro:Development dordal$ 
```

Now edit `www/config.xml` to change some values to 'Test123' (from the 'Hello World' defaults):

```
<name>Test123</name>
<description>
    Test123
</description>
<author email="support@phonegap.com" href="http://phonegap.com">
    Test123 Team
</author>
```

Build the app:

```
David-Ordals-MacBook-Pro:test123 dordal$ phonegap build ios
[phonegap] detecting iOS SDK environment...
[phonegap] using the local environment
[phonegap] adding the iOS platform...
[phonegap] compiling iOS...
[phonegap] successfully compiled iOS app
David-Ordals-MacBook-Pro:test123 dordal$ 
```

Now look at the build file, `platforms/ios/Test123/config.xml`:

```
<widget id="io.cordova.helloCordova" version="2.0.0" xmlns="http://www.w3.org/ns/widgets">
    <name>Hello Cordova</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
```

**Note how the values are still the hello world defaults, and have not been changed to the new `config.xml` values?** N.B. Some values, such as the `<preference>` blocks, do seem to get copied across. It's values like `<name>`, `<description>` or `<content>` that don't work.

**Comment by filmaj** [comment] 2017-04-19 17:50
Cannot reproduce this issue. Whatever values I drop in to config.xml are properly propagated through to the platform-specific config.xml's.

Closing.

**Closed by filmaj** 2017-04-19 17:50 UTC
Labels: enhancement, needs-verification, phonegap-build
