### ISSUE TITLE
Analytics has an unsafe use of an empty array

### ISSUE THREAD

**Issue by purplecabbage** [phonegap/phonegap-cli#625] opened 2016-07-18 20:45 UTC
`> phonegap remote`
produces error output :
phonegap-cli/lib/cli/util/sanitize-args.js:111
                        if (args[1].toLowerCase() == "login") {

**Comment by filmaj** [comment] 2017-04-21 15:26
I cannot reproduce on latest phonegap-cli. And it looks like @purplecabbage did commit a fix. Closing this.

**Closed by filmaj** 2017-04-21 15:26 UTC
Labels: bug
