### ISSUE TITLE
Phonegap: Can not find script file  "C:\res\windows\zip.js"

### ISSUE THREAD

**Issue by icphoton** [phonegap/phonegap-cli#542] opened 2015-06-27 10:22 UTC
When I try and enter

> phonegap build android
> into the cmd I just get back the error 'Can not find script file "C:\res\windows\zip.js"'
> Any help is appreciated 
> Thanks

**Comment by Makeshift** [comment] 2015-07-13 12:06
Same issue here - Tried on Win7 and Win8.1, my issue is over on the node build repo:
https://github.com/phonegap/node-phonegap-build/issues/61

**Comment by mdsomerfield** [comment] 2015-07-14 11:36
Same issue here on Windows 8.1.

**Comment by fryck** [comment] 2015-07-16 08:07
Same issue here on Windows 8.1 !!!

**Comment by mwbrooks** [comment] 2015-09-14 22:44
Moving to the Backlog. I'll try to reproduce this issue this week!

**Comment by filmaj** [comment] 2017-04-20 17:50
I could not reproduce this on Windows 8.1 using phonegap-cli@6.5.0.

Without the Android SDK installed I get this, which provides a clear error message:

```
C:\Users\labuser\src>phonegap create test

You have been opted out of telemetry. To change this, run: cordova telemetry on.

Creating a new cordova project.

Using cordova-fetch for phonegap-template-hello-world

C:\Users\labuser\src>cd test

C:\Users\labuser\src\test>phonegap build android
[phonegap] executing 'cordova platform add --save android' ...
[phonegap] completed 'cordova platform add --save android'
[phonegap] executing 'cordova build android ' ...
Error: Failed to find 'ANDROID_HOME' environment variable. Try setting setting i
t manually.
Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to inclu
de path to valid SDK directory.
```

With the Android SDK installed and the `PATH` and `ANDROID_HOME` environment variables set up properly, I get this (note I had to specifically install a newer cordova-android to support the latest Android SDK):

```
C:\Users\labuser\src>phonegap create test

You have been opted out of telemetry. To change this, run: cordova telemetry on.

Creating a new cordova project.

Using cordova-fetch for phonegap-template-hello-world

C:\Users\labuser\src>cd test

C:\Users\labuser\src\test>phonegap platform add android@6.2.1
Adding android project...

Creating Cordova project for the Android platform:

        Path: platforms\android

        Package: com.phonegap.helloworld

        Name: helloworld

        Activity: MainActivity

        Android target: android-25

Subproject Path: CordovaLib
Android project created with cordova-android@6.2.1

Installing "cordova-plugin-battery-status" for android

Installing "cordova-plugin-camera" for android

Installing "cordova-plugin-compat" for android

Installing "cordova-plugin-console" for android
Installing "cordova-plugin-contacts" for android

Installing "cordova-plugin-device" for android

Installing "cordova-plugin-device-motion" for android

Installing "cordova-plugin-device-orientation" for android

Installing "cordova-plugin-dialogs" for android

Installing "cordova-plugin-file" for android

Dependent plugin "cordova-plugin-compat" already installed on android.

The Android Persistent storage location now defaults to "Internal". Please check
 this plugin's README to see if your application needs any changes in its config
.xml.

If this is a new application no changes are required.

If this is an update to an existing application that did not specify an "Android
PersistentFileLocation" you may need to add:

      "<preference name="AndroidPersistentFileLocation" value="Compatibility" />
"
to config.xml in order for the application to find previously stored files.

Installing "cordova-plugin-file-transfer" for android

Dependent plugin "cordova-plugin-file" already installed on android.

Installing "cordova-plugin-geolocation" for android

Installing "cordova-plugin-globalization" for android

Installing "cordova-plugin-inappbrowser" for android

Installing "cordova-plugin-media" for android

Dependent plugin "cordova-plugin-file" already installed on android.

Installing "cordova-plugin-media-capture" for android

Dependent plugin "cordova-plugin-file" already installed on android.

Installing "cordova-plugin-network-information" for android

Installing "cordova-plugin-splashscreen" for android

Installing "cordova-plugin-statusbar" for android

Installing "cordova-plugin-vibration" for android

Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android gr
eater than 4.0. If you have a previous platform version, you do *not* need this
plugin since the whitelist will be built in.

C:\Users\labuser\src\test>phonegap build android
[phonegap] executing 'cordova build android ' ...
[phonegap] completed 'cordova build android --no-telemetry'
```

Closing this issue. If someone is still experiencing this issue, please feel free to re-open and provide more details, like node/npm version, phonegap-cli version, state of Android SDK install, whether or not you have the `ANDROID_HOME` environment variable set correctly, and any and all command line output, please.

**Closed by filmaj** 2017-04-20 17:50 UTC
Labels: bug
