### ISSUE TITLE
Phonegap deletes my code in www when i add new plugin

### ISSUE THREAD

**Issue by grupored2016** [phonegap/phonegap-cli#621] opened 2016-07-01 18:06 UTC
Phonegap deletes my code in www each time that i run command  phonegap local plugin add 'xxxx'

**Comment by surajpindoria** [comment] 2016-07-01 18:23
Hi @grupored2016,

What version of phonegap are you using? Also what are your node and npm versions?

**Comment by grupored2016** [comment] 2016-07-13 00:52
Hi @surajpindoria ,

I'm using phonegap 6.2.7, npm 2.10.1 and node.js 0.12.4

Thanks

**Comment by surajpindoria** [comment] 2016-07-15 22:21
I am unable to reproduce this. The `local` command has been deprecated and when used will just strip that keyword from the original command. Can you try this using just `phonegap plugin add <plugin>` and see if you get the same result?

@grupored2016

**Comment by grupored2016** [comment] 2016-07-16 00:52
This is before run a command  

![image](https://cloud.githubusercontent.com/assets/20247057/16891744/c78e4cb8-4ab3-11e6-9fb1-67b1879466df.png)

and this is after run a command

![image](https://cloud.githubusercontent.com/assets/20247057/16891767/43c28c86-4ab4-11e6-9a36-7d71ab9d11d5.png)

Every time that I add a plugin I get the same result : deletes my code in www
The problem started when i update phonegap to 6.2.7 version :(

Thanks

**Comment by surajpindoria** [comment] 2016-07-18 20:57
This is actually the intended behavior, `<project>/platforms/android/assets/www/` will be regenerated whenever the project is prepared. If you want files to be added to the project each time you should place them in `<project>/www/` folder.

**Comment by grupored2016** [comment] 2016-07-19 15:38
Thanks @surajpindoria 

It works, but still regenerate my configurations files like AndroidManifest and deletes my configurations like version or orientation configuration.

There is any way to install plugins without regenerate my files? 

Thanks.

**Comment by surajpindoria** [comment] 2016-07-19 17:00
No there is not. But for configurations like version and orientation you can use preferences in your `config.xml` to set these values and they will update the `AndroidManifest.xml` accordingly.

https://cordova.apache.org/docs/en/latest/config_ref/#preference

**Comment by surajpindoria** [comment] 2016-07-25 22:28
Hi @grupored2016,

I am going to consider this resolved and close this issue. If you have any other questions feel free to post them here or file another issue.

**Closed by surajpindoria** 2016-07-25 22:28 UTC
