### ISSUE TITLE
Cannot find module './lib/run', when running ´phonegap run IOS´

### ISSUE THREAD

**Issue by ignacio-chiazzo** [phonegap/phonegap-cli#653] opened 2016-10-14 13:17 UTC
### PhoneGap CLI, node & npm versions

Phonegap -v : 6.3.3
npm -v : 3.3.6
node -v : 5.0.0

Note: I tried with others version of node, particularly with the following : 
        v0.10.47
        v0.12.0
        v0.12.12
        iojs-v2.0.0
        v4.0.0
        v4.2.2
        v5.0.0
        v6.8.0
### Expected Behaviour

Run the project
### Actual Behavior

The error that I am getting is the following : 

> add to body class: platform-ios
> 
> Running command: /Users/ignacio/Documents/Projects/kinnecting_app/platforms/ios/cordova/run 
> 
> module.js:339
>     throw err;
>     ^
> 
> Error: Cannot find module './lib/run'
>     at Function.Module._resolveFilename (module.js:337:15)
>     at Function.Module._load (module.js:287:25)
>     at Module.require (module.js:366:17)
>     at require (module.js:385:17)
>     at Object.<anonymous> (/Users/ignacio/Documents/Projects/kinnecting_app/platforms/ios/cordova/run:23:13)
>     at Module._compile (module.js:425:26)
>     at Object.Module._extensions..js (module.js:432:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:311:12)
>     at Function.Module.runMain (module.js:457:10)
> 
> Error: /Users/ignacio/Documents/Projects/kinnecting_app/platforms/ios/cordova/run: Command failed with exit code 1
### Steps to Reproduce

run PhoneGap run ios

**Comment by surajpindoria** [comment] 2016-10-17 18:03
Hi @ignacio-chiazzo,

I have just tested this on my machine using a few different versions of node that you described and am unable to reproduce this issue. Can you try removing iOS from your project, `phonegap platform rm ios`, and then re-adding it, `phonegap platform add ios`.

If this doesn't resolve your issue, there could be something wrong with your installed `phonegap`. I would also try reinstalling that as well, `npm uninstall -g phonegap`, `npm install -g phonegap`.

**Comment by filmaj** [comment] 2017-04-21 16:43
Closing this issue as reporter has not responded to requests to help. If you are still experiencing this problem, feel free to re-open the issue and provide us with more details.

**Closed by filmaj** 2017-04-21 16:43 UTC
Labels: question
