### ISSUE TITLE
Plugins storing to platform_www rather than www causing issues

### ISSUE THREAD

**Issue by Danbardo** [phonegap/phonegap-cli#583] opened 2016-03-01 07:45 UTC
Hey,

I recently updated my phonegap to the latest version 6.0.1.

I've created a test application with some plugins like admobpro, splashscreen and whitelist. I have noticed that when I create the android project the plugin .js files and the cordova_plugins.js is being saved to the platform_www folder, rather that the assests/www folder.

Now whenever my apps load up I get the following error:
Unable to open asset URL: file:///android_asset/www/cordova_plugins.js

Which is causing none of the plugins to function.

At the moment I have resolved the issue by copying the files/folders
platform_www/cordova_plugin.js
platform_www/plugins

to the assets/www folder. While this fixes the problem, I thought I'd raise this issue in case there is a better solution / if any one else is facing this problem.

Thanks

**Comment by surajpindoria** [comment] 2016-03-01 20:42
Hi @Danbardo,

Storing the plugin.js / cordova_plugins.js is a feature that was added to Cordova awhile back. But I just tried this and saw that those files exist in both locations on my system. Are you doing any other modifications to the test project you are working with?

**Comment by Danbardo** [comment] 2016-04-05 02:35
Hey @surajpindoria,

Thanks for your response,

I have just tested this again with iOS as well as android.

My steps:
Create a new project
Add some plugins
Add ios and android platforms

After these steps there the cordova_plugins.js is only located in the platforms_www and not the www, for both platforms I have to manually copy the plugins folder and cordova_plugins.js from the platforms_www folder into the www folder.

Commands I am using:
phonegap create myApp --id "com.my.app" --name "My App"
phonegap plugin add org.apache.cordova.geolocation
phonegap plugin add cordova-plugin-statusbar
phonegap platform add ios
phonegap platform add android

**Comment by surajpindoria** [comment] 2016-04-05 23:27
Once you add the platform you need to prepare it. Running `phonegap prepare ios` and `phonegap prepare android` properly copies over cordova_plugins.js and plugins folder into www.

**Comment by filmaj** [comment] 2017-04-20 23:05
I am unable to reproduce this issue. After `platform add`, cordova under the hood should be automatically issuing a `prepare`. 

Closing - if you want to work on this issue with me to try to dig up what is going on, feel free to re-open it.

**Closed by filmaj** 2017-04-20 23:05 UTC
Labels: bug
