### ISSUE TITLE
Received memory warning and then crash app in ios

### ISSUE THREAD

**Issue by skyblue89** [phonegap/phonegap-cli#587] opened 2016-03-31 21:06 UTC
Using
phonegap 6.0.3 
ios 9.3 
xcode 7

Rendering a site inside an iframe is causing that my app eventually crash in ios

**Comment by filmaj** [comment] 2017-04-21 15:13
Closing this issue. We have nothing to go on to reproduce this, and I could not reproduce using latest phonegap-cli and iOS. @skyblue89 if you still are experiencing this issue, please re-open and provide more details as to the reproduction case.

**Closed by filmaj** 2017-04-21 15:13 UTC
Labels: bug
