### ISSUE TITLE
`phonegap run ios --device` fails silently if `ios-deploy` is not installed

### ISSUE THREAD

**Issue by atuttle** [phonegap/phonegap-cli#523] opened 2015-03-27 14:57 UTC
I am on a brand new machine setting things up from scratch. OSX 10.10.2. I installed `phonegap` via npm (though it required the use of `sudo`), and had to jump through a few hoops to get `ios-sim` to install through npm, too (sorry, didn't write them down and that was late last night)...

Now I'm trying to run `phonegap run ios --device` and nothing happens:

```
$ phonegap run ios --device
[phonegap] executing 'cordova run ios --device'...
[phonegap] completed 'cordova run ios --device'
```

Since nothing happened on my connected ios device, I decided to try again with the `--verbose flag` and saw this error:

```
Running command: [snip]/mobile/platforms/ios/cordova/run --device

Error: ios-deploy was not found. Please download, build and install version 1.2.0 or greater from https://github.com/phonegap/ios-deploy into your path. Or 'npm install -g ios-deploy' using node.js: http://nodejs.org/

Command finished with error code 1: [snip]/mobile/platforms/ios/cordova/run --device

ERROR running one or more of the platforms: Error: [snip]/mobile/platforms/ios/cordova/run: Command failed with exit code 1
You may not have the required environment or OS to run this project

[phonegap] completed 'cordova run ios --device --verbose'
```

I will be installing that dependency manually and trying again, but I thought you should know so you can surface that error without the `--verbose` flag.

**Comment by ericman93** [comment] 2015-05-22 18:08
+1

**Comment by micky2be** [comment] 2015-06-03 02:17
+1

**Comment by santoshnaidu009** [comment] 2015-06-07 03:35
+1

**Comment by si458** [comment] 2015-06-24 17:39
+1

**Comment by andrewmilson** [comment] 2015-07-10 06:14
+1

**Comment by jhitchcock** [comment] 2015-08-11 17:00
+1

**Comment by karlingen** [comment] 2015-08-18 13:10
+1

**Comment by olimortimer** [comment] 2015-08-28 10:22
Thanks for the heads up!

**Comment by mwbrooks** [comment] 2015-09-15 17:45
Thanks for the heads up @atuttle!

I've went ahead and created a milestone to improve this experience. The main consideration is non-OS X users because they cannot install/compile `ios-sim` and `ios-deploy`. I'll use this issue to track the progress of bundling these tools and ensuring that Cordova is able to leverage the local copies.

**Comment by c410cs** [comment] 2016-02-24 15:27
When this error happen, I am desesperated, but I just desplugged my iPhone device from my MacBook and.. SURPRISE, all works fine!

**Comment by filmaj** [comment] 2017-04-19 20:38
Just an update for this issue: in the latest phonegap-cli, if you run without the `-d` or `--verbose` flag, this is what you will see (on macOS Sierra):

```
Error: spawn ios-deploy ENOENT
```

With `-d`, you will see:

```
Error: spawn ios-deploy ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

So, I am not sure that the original issue with respect to 'failing silently' is still applicable here. Even in non-verbose mode, `ENOENT` error with respect to `ios-deploy` makes it relatively clear what the issue is, I think.

Perhaps worth closing the issue?

Thoughts @mwbrooks / @surajpindoria ?

**Comment by surajpindoria** [comment] 2017-04-19 20:53
Agreed, if it is displaying an error message then I think it is safe to close it.

**Comment by filmaj** [comment] 2017-04-19 21:00
Alright, if others disagree and would like to see more specific error messaging here, please speak up + reopen the issue. In the mean time, closing.

**Closed by filmaj** 2017-04-19 21:00 UTC
Labels: bug
