### ISSUE TITLE
Add --save by default to 'phonegap plugin add ' 

### ISSUE THREAD

**Issue by maverickmishra** [phonegap/phonegap-cli#672] opened 2016-12-13 23:35 UTC
'phonegap plugin add' should perform  'phonegap plugin add --save' and then update the details in config.xml of the project. The same --save logic should also work when we remove a plugin.

**Comment by brodybits** [comment] 2017-01-31 17:19
FYI https://github.com/apache/cordova-cli/pull/266 fixes this in Cordova CLI if it is integrated ref: <https://issues.apache.org/jira/browse/CB-12008>

**Comment by surajpindoria** [comment] 2017-01-31 18:21
Hi @brodybits,

While this functionality will be added to the cordova CLI it doesn't work when using cordova as a module, like we do in the phonegap CLI. So we still need to add this on our end.

**Comment by filmaj** [comment] 2017-04-21 19:05
This is a duplicate of #651. Closing.

**Closed by filmaj** 2017-04-21 19:05 UTC
Labels: enhancement
