### ISSUE TITLE
No way to lock iPad orientation to landscape via config.xml

### ISSUE THREAD

**Issue by martenbiehl** [phonegap/phonegap-cli#405] opened 2014-08-29 14:44 UTC
Hi!

I can make none of the ways work that are described here http://docs.build.phonegap.com/en_US/2.9.0/configuring_config_file_element.md.html 

I am on version 3.5.0-0.21.14 of phonegap installed via npm.

To reproduce:

```
npm install -g phonegap
phonegap create orientation-test
```
## 1. edit config.xml

`<preference name="orientation" value="landscape" />`
`phonegap build ios`
open `platforms/ios/HelloWorld/HelloWorld-Info.plist` to check that the setting had no effect
## 2. edit config.xml to contain

```
<gap:config-file platform="ios" parent="UISupportedInterfaceOrientations" overwrite="true">
        <array>
            <string>UIInterfaceOrientationLandscapeLeft</string>
            <string>UIInterfaceOrientationLandscapeRight</string>
        </array>
</gap:config-file>
<gap:config-file platform="ios" parent="UISupportedInterfaceOrientations~ipad" overwrite="true">
        <array>
            <string>UIInterfaceOrientationLandscapeLeft</string>
            <string>UIInterfaceOrientationLandscapeRight</string>
        </array>
</gap:config-file>
```

`phonegap build ios`
open `platforms/ios/HelloWorld/HelloWorld-Info.plist` to check that the setting had no effect

Is this a bug or is some information missing from the documentation? I can find no information anywhere online to make this work without editing the pList file directly. Yet, I would rather avoid this to not having to manage multiple configuration files and being able to keep up to date with phonegap.

Thanks
Marten

**Comment by TianleZhang** [comment] 2015-02-25 11:20
Same issue here

**Comment by iharosi** [comment] 2015-03-11 10:40
Same issue!
```
devacc at macmini in ~
$ cordova -v
4.3.0

devacc at macmini in ~
$ phonegap -v
4.2.0-0.24.2

devacc at macmini in ~
$ node -v
v0.12.0

devacc at macmini in ~
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.2
BuildVersion:	14C1510
```

**Comment by pbihler** [comment] 2015-03-26 22:12
Still the same issue, and I don't have the option to set things manually in the plist, since its generated on build in my setup.

**Comment by SergeySnegirev** [comment] 2015-04-01 20:05
Still the same issue, incredibly annoying for Phonegap Build users.

**Comment by LukaszC** [comment] 2015-04-19 14:10
+1

**Comment by tjsail33** [comment] 2015-06-20 02:16
+1.

**Comment by alain-r** [comment] 2015-07-08 08:55
+2

**Comment by SergioRodriguezRuiz** [comment] 2015-07-09 10:50
+ 3 Same issue here.

**Comment by michavonoben** [comment] 2015-07-09 10:53
+4 same issue. iOS 8.4, phonegap 5.1.1

**Comment by ygayl** [comment] 2015-07-12 15:51
+5 same issue. iOs 8.3, cordova 5.0.0

**Comment by bradleyflood** [comment] 2015-07-15 04:32
+6 Cordova `5.1.1`

**Comment by markusv** [comment] 2015-07-20 07:01
+7

**Comment by Xairoo** [comment] 2015-07-25 15:19
+8

**Comment by abruzzihraig** [comment] 2015-07-28 11:51
+9

**Comment by voluntas** [comment] 2015-09-01 05:41
+10

**Comment by smemane** [comment] 2015-10-03 01:02
+11

**Comment by ygayl** [comment] 2015-10-03 02:13
Guys, for those of you still having the issue, I just wrote a simple grunt task to update the plist file and removing the portrait.

```
    grunt.registerTask('updateiOSPlistLandscapeOnly', function () {
        var plist = require('plist'),
            appName = 'Your Super App',
            plistFilepath = path.resolve() + '/' + 'platforms/ios/' + appName + '/' + appName + '-Info.plist',
            plistJson = plist.parseFileSync(plistFilepath);
        
            plistJson['UISupportedInterfaceOrientations~ipad'].forEach(function(value, index){
                if (value && value.indexOf('Portrait') > -1){
                    plistJson['UISupportedInterfaceOrientations~ipad'].splice(index, 1);
                }
            });
            var plistObj = plist.build(plistJson);
            grunt.verbose.writeln('****Updating plist: removing portrait****');
            grunt.file.write(plistFilepath, plistObj);
    });
```

And depending on your build management, either add it to your build workflow (grunt, gulp) either you can it to the hooks.
For the last one, within your before_build hooks directory (create it if you don't have it yet), you can just add the following code in a new file (010_remove_portrait.js for example).


```
#!/usr/bin/env node

var exec = require('child_process').exec;
if (process.env.CORDOVA_CMDLINE.indexOf('ios') > -
    function puts(error, stdout, stderr) {
        console.log(stdout)
    }
    exec("grunt updateiOSPlistLandscapeOnly", puts);
```

An easier and cleaner solution would be to write the code directly within the hooks nodejs script.
But as my build was using grunt already with a lot of other tasks, I just went with it.

**Comment by SergeySnegirev** [comment] 2015-10-07 11:56
@ygayl Thanks but this won't help those who use PhoneGap Build online. So we really need that bug fixed.

**Comment by kishorekumaru** [comment] 2015-10-13 23:16
The issue with IOS 9.0 iPhone devices also, I am using the following lang version

Cordova : 5.3.3
Phonegap : 5.2.0
config.xml : 	<preference name="orientation" value="portrait" />
I have tried cordova-plugin-screen-orientation, it didnt help :+1: 
iPhone 6 plus : IOS ( 9.0.2) not working 

Any help?

**Comment by stinker** [comment] 2015-11-10 16:15
+12

**Comment by cmartinezv** [comment] 2016-04-23 18:19
+13

**Comment by ruudruud** [comment] 2016-05-15 11:02
+14 This is a very annoying bug.

**Comment by filmaj** [comment] 2017-04-19 20:15
I cannot reproduce this with the latest phonegap-cli.

I created a project, added `<preference name="Orientation" value="landscape" />` to my `config.xml`, ran `phonegap build ios`, and I see this under `platforms/ios/HelloWorld/HelloWorld-Info.plist`:

```
➔ ack -i orientation platforms/ios/HelloWorld/HelloWorld-Info.plist
    <key>UISupportedInterfaceOrientations</key>
      <string>UIInterfaceOrientationLandscapeLeft</string>
      <string>UIInterfaceOrientationLandscapeRight</string>
    <key>UISupportedInterfaceOrientations~ipad</key>
      <string>UIInterfaceOrientationLandscapeLeft</string>
      <string>UIInterfaceOrientationLandscapeRight</string>
    <key>UIInterfaceOrientation</key>
      <string>UIInterfaceOrientationLandscapeLeft</string>
```

Closing.

**Closed by filmaj** 2017-04-19 20:15 UTC
Labels: bug, enhancement

**Comment by iharosi** [comment] 2017-04-19 20:18
So it took 3 years to fix this. Unbelievable. 🥇 👍 XD :D

**Comment by filmaj** [comment] 2017-04-19 20:27
@iharosi incorrect. [The issue existed in Apache Cordova land and took one year to fix](https://issues.apache.org/jira/browse/CB-6105).

PhoneGap and Apache Cordova are open source projects, and you are more than welcome to help out and fix things. Snark is, generally speaking, unhelpful, and quite frankly, demotivating to all of the contributors spending their time on this trying to help folks like yourself.
