### ISSUE TITLE
Phonegap ignoring android sdk setup in config.xml

### ISSUE THREAD

**Issue by CGastrell** [phonegap/phonegap-cli#576] opened 2016-01-20 04:44 UTC
I'm not quite sure if this is a bug or what (since I've been dealing with it for so long), but phonegap seems to ignore the sdk preferences for android in config.xml

Whenever I add android platform the wrong one is being selected as target (one I don't even have). I was wondering if maybe I have something wrong. I even made sure I only have one android API level to be sure. So I wanted to check with you.

This is the output of `android list targets`:

```
Available Android targets:
----------
id: 1 or "android-21"
     Name: Android 5.0.1
     Type: Platform
     API level: 21
     Revision: 2
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : no ABIs.
```

These are the sdk relevant preferences in _config.xml_:

``` xml
    <preference name="android-minSdkVersion" value="14" />
    <preference name="android-targetSdkVersion" value="21" />
    <preference name="android-maxSdkVersion" value="21" />
```

But when I run `phonegap platform add android` I get:

```
Adding android project...

Creating Cordova project for the Android platform:

    Path: platforms/android
    Package: com.myapp.test
    Name: Hello_World
    Activity: MainActivity
    Android target: android-23

Android project created with cordova-android@5.0.0
```

Is this normal? I mean, I'm used to fix this by editing `platforms/android/project.properties` and `platforms/android/CordobaLib/project.properties` files, but shouldn't the API level target come out of the _config.xml_ file?

Thanks

**Comment by msudol** [comment] 2016-01-29 18:50
Phonegap does not necessarily handle all the Android preferences as well as you might like.. I've found that using cordova-custom-config (https://github.com/dpa99c/cordova-custom-config) can help bridge that gap, that way you dont have things in the platforms getting blow out every time you make a build.

**Comment by CGastrell** [comment] 2016-02-01 16:37
Excellent suggestion! I'll dig into it.

On the other hand, I believe either my claim has a point or I've misunderstood the preference configuration.

If the config.xml offers a preference configuration for *android-targetSdkVersion* and then completely ignores it, my doubt is legit: I can't know if its malfunctioning or I have a wrong understanding of what it does. Hence I ask about it here.

If it shouldn't be ignoring it, then it is a **bug**. If it's and old configuration we can't use anymore (somehow we phonegap users are expected to correct this symptom with a solution as the one you mention) it should be stated somewhere or deleted from the docs.

I'm not trying to make a drama about it, I just think it's important to keep consistency between docs and functionality. There are many users out there who may become frustrated and not use it at all. I myself had to run several tests until I figured both the problem and how to overcome it, and it's not the first time. So I just wondered how hard would it be to solve the issue or correct the docs.

Another option would be to change the configuration option to *android-tryToTargetSdkVersion*, so we know it's kinda of a long shot, but I don't think that would be better, just more accurate :)

**Comment by mwbrooks** [comment] 2016-02-01 23:58
Hey @CGastrell, this functionality is handled by Apache Cordova under-the-hood. I agree, on the surface is looks like it's a bug and Android should not be installed using a different target. However, that target is likely defined by the version of `cordova-android` used and not by the `config.xml`.

@macdonst @infil00p can either of you shed some light on this? Should we file it as an Apache Cordova issue?

**Comment by gustavocampos** [comment] 2016-06-30 20:53
I'm having the same issue, but it used to work with cordova-android@4.1.1, I've been building 2 apps for months like this on PhoneGap Build, I had to move to 5.1.1 due to Android 6 permission system and android-minSdkVersion stopped working.

**Comment by azachar** [comment] 2016-07-13 17:53
+1

**Comment by mradcliffe** [comment] 2016-09-02 12:21
I ran into this with PhoneGap Build (running phonegap-cli), but not phonegap-cli (6.3.0) or cordova (6.3.0). I use a config.xml with `android-minSdkVersion` and `android-targetSdkVersion` set to 19 and 23 respectively.

I inspected the AndroidManifest.xml using `aapt dump xmltree <apk> AndroidManifest.xml` on the builds with the following results.

Tool               | Result 
-------------- | -------------------------- |
cordova 6.3.0 | minSdkVersion set to 19 and targetSdkVersion set to 23
phonegap 6.3.0 | minSdkVersion set to 19 and targetSdkVersion set to 23
PhoneGap Build (using phonegap 6.3.0) | minSdkVersion is set to 14, targetSdkVersion is missing

I can conclude that there is no issue in phonegap-cli directly, but there is a bug with the PhoneGap Build process, and my assumption is that PhoneGap Build is hardcoding a minimum SDK version and does not use the config.xml for these (and possibly other) configuration values.

**Comment by mredbishop** [comment] 2017-03-02 21:34
@mradcliffe Yes, I agree with your conclusion. It's still doing this for various preferences (6 months later) including but not limited to the fullscreen setting and the android:windowSoftInputMode. This is a real pain in the ass, as phonegap build is great for deploying to testers. Building locally using the CLI does not have this issue.

**Comment by wildabeast** [comment] 2017-03-03 03:08
Re: Phonegap Build (PGB)

I believe that just because you're not seeing your chosen `minSdkVersion` and `targetSdkVersion` in the manifest of the compiled apk, that doesn't mean they haven't been set. For example, if you set:

    <preference name="android-minSdkVersion"      value="19" />
    <preference name="android-targetSdkVersion"   value="23" />

If you use apktool to unpack the compiled apk from PGB, you won't see these values in AndroidManifest.xml, but you will see them in the properties in apktool.yml.

@mredbishop As for `fullscreen` and `windowsoftinputmode`, I'd suggest opening a thread in the [Phonegap Build Discussion forum](https://forums.adobe.com/community/phonegap/build). Best place for PGB-related issues.

Side note: on PGB you can tweak the manifest in any way you want using the [config-file element](http://docs.phonegap.com/phonegap-build/configuring/config-file-element/). Handy if you're looking to change unsupported manifest properties, or if you're finding preferences aren't working as expected.

**Comment by mradcliffe** [comment] 2017-03-03 13:05
@wildabeast: `minSdkVersion` and `targetSdkVersion` were definitely not working in PGB builds back in August. Manual testing confirmed that the PGB build could be installed on Android devices running on older software than what was listed.

I checked a build I had to double-check. The `apktool.yml` file was also not updated with the correct values just as I outlined in the table in my comment above. Again, it was PGB that was the issue. Cordova and Phonegap-cli generated builds respected config.xml.

**Comment by mredbishop** [comment] 2017-03-03 15:23
Absolutely the same here. This issue is PhoneGap Build which I guess must
not use the latest/same phonegap-cli under the hood?

**Comment by wildabeast** [comment] 2017-03-06 22:49
@mradcliffe do you have an App currently on Phonegap Build that exhibits this? If so, can you share the App ID? If you'd like to keep it private you can email to build at phonegap.com and reference this issue.

**Comment by filmaj** [comment] 2017-04-20 20:23
While the output from `phonegap platform add android` is confusing, I would double-check your `AndroidManifest.xml`. I tried reproducing this situation and the correct min, max and target SDK versions were set in my Manifest.

The reason for this is a detail regarding the implementation of cordova-android that I will try to explain. The parsing of config.xml is done not at the time of `platform add android` (which actually runs the [`create` script within cordova-android](https://github.com/apache/cordova-android/blob/master/bin/create)), but rather during the `prepare` command, which is run _after_ the `create` script is invoked, but before the `phonegap platform add` command is finished. The output from the `create` script that you saw, `Android target: android-23` is because by default it uses the latest android target available in the wild as the target. It is once this `create` is complete that the `config.xml` file is parsed, the max/min/target SDK version are figured out, and that is dropped into the `AndroidManifest.xml` file.

If I run with a recent phonegap-cli version (6.4.7), you can see that the correct attributes are interpolated into the Manifest:

```
~/src via ⬢ v6.10.1
➔ phonegap create preftest-pg
Creating a new cordova project.

Using cordova-fetch for phonegap-template-hello-world

~/src via ⬢ v6.10.1
➔ cd preftest-pg

~/src/preftest-pg via ⬢ v6.10.1
➔ vim config.xml # remove the default minSdkVersion=14 that comes with phonegap-template-hello-world, and add target + max.

~/src/preftest-pg via ⬢ v6.10.1
➔ ack SdkVersion config.xml
        <preference name="android-minSdkVersion" value="19" />
        <preference name="android-targetSdkVersion" value="20" />
        <preference name="android-maxSdkVersion" value="21" />

➔ phonegap platform add android
Adding android project...

Creating Cordova project for the Android platform:

	Path: platforms/android
	Package: com.phonegap.helloworld

	Name: helloworld
	Activity: MainActivity

	Android target: android-24

Subproject Path: CordovaLib

Android project created with cordova-android@6.0.0

# a whole bunch of plugin installation output that I will skip

~/src/preftest-pg via ⬢ v6.10.1
➔ ack uses-sdk platforms/android/AndroidManifest.xml
    <uses-sdk android:maxSdkVersion="21" android:minSdkVersion="19" android:targetSdkVersion="20" />
```

So, even though on the initial `platform add` the output confusingly mentioned an android target of android-24, you can see that the result in the manifest is as desired.

As such, I am going to close this issue down as no longer an issue. If you feel the original issue is not resolved here, please feel free to re-open and I will do my best to help you.

**Closed by filmaj** 2017-04-20 20:23 UTC
Labels: question

**Comment by TheBearF8** [comment] 2018-01-14 21:39
I am also seeing the same thing
Android target: android-24   is being taken from the compileSdkVersion   or   cdvCompileSdkVersion

targetSdkVersion maybe set to  19  but if  cdvCompileSdkVersion / android-24 then it will build for android-24 and not work on <24 regardless of minSdk and targetSdk 

Would love a solution

**Comment by chrisunderdown** [comment] 2019-02-13 11:25
The problem for me was in [cordova-plugin-browsertab][1].


You need to change line 1 of `my_project/plugins/cordova-plugin-browsertab/src/android/BrowserTab.gradle` to

    def minSdkVersion = 19

Make sure you have the minimum SDK added to your `config.xml`

    <preference name="android-minSdkVersion" value="19" />
Then remove and add cordova-android by:

    cordova platform remove android
    cordova platform add android


  [1]: https://github.com/google/cordova-plugin-browsertab

**Comment by joshsutterfield** [comment] 2019-05-03 06:00
The problem is not *really* in the plugins. Indeed I am having the same issue with cordova-plugin-browsertab, but it sees no set minimum, and supplies its own, 16. The build.gradle which loads this in is broken because it ignores all other numbers, takes the low minimum and wipes out the other minimum it had (project.ext.defaultMinSdkVersion = 19 which is set in the build.gradle one level up). 19 would be sufficient for me, but indeed, there is nothing set up to look for the minSdkVersion set in the AndroidManifest and propagating from config.xml.

I've seen several posts in different places suggesting the plugins are the issue, but the build.gradle is the one actively loading any gradle stuff from plugins, and promptly mishandling it even if it was safe enough. Indeed the browsertab plugin is doing nothing crazy: it sets its minimum if it is not superceded by something else. Setting it to a higher number is a workaround.
