### ISSUE TITLE
Node Library Section in Readme.md needs more content

### ISSUE THREAD

**Issue by theaccordance** [phonegap/phonegap-cli#567] opened 2015-12-28 17:43 UTC
The "Node Library" section of Readme.md is lacking a lot of content that would be valuable to users who are trying to use the module within projects.  

Please either include relevant information for this section (methods available, etc) or a link to documentation that clarifies this to the user.

**Comment by mwbrooks** [comment] 2016-01-04 18:00
Hey @theaccordance, it's great to hear that you're using the PG CLI as a node module. I wrote that documentation when we original created the PG CLI, but I've only heard of a few people using it programmatically.

For now, the most accurate documentation would be the source code.

- All of the available methods are [listed here](https://github.com/phonegap/phonegap-cli/blob/master/lib/phonegap.js#L30-L41).
- Each method should contain a dox-style comment block (e.g. [phonegap.create(options, callback)](https://github.com/phonegap/phonegap-cli/blob/master/lib/phonegap/create.js#L28-L49)).

It would be nice to see these documentation rendered out to an API webpage. If there's more interested, I'd be open to doing more of the leg work.

**Comment by filmaj** [comment] 2017-04-20 18:39
I'm going to close this as a duplicate of #16, where we want to investigate generating the documentation programmatically.

**Closed by filmaj** 2017-04-20 18:39 UTC
Labels: enhancement
